name = "anime-wall"
compatibility_date = "2023-12-01"
compatibility_flags = ["nodejs_compat"]
main = "_worker.js"

[build]
command = "npm run build"

# Configure module externals for worker
[rules]
type = "ESModule"
[rules.build]
external = ["server-only"]

[build.upload]
format = "modules"
dir = ".next"
main = "_worker.js"
module_rules = [
  { type = "Text", globs = ["**/*.js"], fallthrough = true }
]

[env.production]
workers_dev = true
vars = { ENVIRONMENT = "production" }

[env.preview]
workers_dev = true
vars = { ENVIRONMENT = "preview" }