name = "anime-wall"
compatibility_date = "2023-12-01"
compatibility_flags = ["nodejs_compat"]

# Use the correct main file
main = "_worker.js"

# Build command that integrates the Cloudflare adapter
[build]
command = "npm run build"
[build.upload]
format = "service-worker"

[build.external]
packages = ["server-only", "@cloudflare/next-on-pages/middleware"]

[site]
bucket = ".next/static"

[env.production]
workers_dev = true
vars = { ENVIRONMENT = "production" }

[env.preview]
workers_dev = true
vars = { ENVIRONMENT = "preview" }