name = "kibe-wall"
compatibility_date = "2025-03-12"
compatibility_flags = ["nodejs_compat"]

# Use the correct main file
main = "_worker.js"

# Build command that integrates the Cloudflare adapter
[build]
command = "npx @cloudflare/next-on-pages@1"

[site]
bucket = ".next/static"

[env.production]
workers_dev = true
vars = { ENVIRONMENT = "production" }

[env.preview]
workers_dev = true
vars = { ENVIRONMENT = "preview" }