name = "kibe-wall"
main = "_worker.js"
compatibility_date = "2025-03-12"
compatibility_flags = ["nodejs_compat"]

# Next.js output
[build]
command = "npm run build"

# Configure the static assets
[site]
bucket = ".next/static"

# Configure routes for the Worker
[env.production]
workers_dev = true

[env.preview]
workers_dev = true

# Configure environment variables if needed
[vars]
# Add your environment variables here if needed
# API_KEY = "" 